### ISSUE TITLE
feat: show the next line with few info as pair

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#26]

**Comment by kaile256** [comment]
Some syntaxes of particular coding styles prefer the prev line in virtual text:

```cpp
int main()
{
    int foo;
    ...
}
```

In this case, Doppelganger should show `int main()` rather than `int foo;`.

However, most of filetypes also have dictionary, if-statement, etc., for which Doppelganger should show the previous line.

```cpp
if (foo)
{
   ...
}
```

So it must include a detection whether the next line is to be shown or the previous line is.
And the detection cannot depend only on current filetype.

**Comment by kaile256** [comment]
## TODO
- [ ] When the shown line exactly matched pattern, show the line above.
- [ ] Add `g:doppelganger#text#filetypes_to_show_contents` which is set to `[ 'json' ]` as default.
- [ ] Add `b:doppelganger_text_show_contents`

**Comment by kaile256** [comment]
- [ ] Recursive search for such codes as below:
```cpp
int
foo(
    bar,
    baz,
    qux,
)
{
   // do something
} // <- show `foo(...) {...}` in virtualtext here.
```
