### ISSUE TITLE
feat(popup): show target info in popup/floating window

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#27]
It will no longer be called Doppelganger, but it's informative that a popup shows a target line with the lines around.

## TODO
- [x] Add `autoload/doppelganger/search.vim` and move the related functions there.
- [ ] Add `autoload/doppelganger/popup.vim` and define functions.
- [ ] Add commands to show a popup in `plugin/doppelganger.vim`

**Comment by kaile256** [comment]
Come to think, it's sufficient to type `%` to get the lines around the other end of pair.
