### ISSUE TITLE
feat(search): add autoload/doppelganger/search.vim

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#28]
It'll make it easier to add derivative features.
Related to #27 .

**Comment by kaile256** [comment]
## TODO

- [ ] `doppelganger#search#get_follower(lnum)` will return `[lnum, pat_leader]`.
- [ ] `doppelganger#search#get_open(lnum)` will return `[lnum, pat_open]`.
- [ ] `doppelganger#search#get_open(lnum, 'n')` should save the position as vim's built-in `search()`.

### Provided:

```cpp
if (foo) { // <- open
    ...
}; // <- close
```

and

```cpp
do {  // <- leader
   ...
} while (foo); // <- follower
```

**Comment by kaile256** [comment]
Reject `doppelganger#search#get_open()` and `doppelganger#search#get_follower()` in the TODO above; instead, adopt `doppelganger#search#get_pair_info()`.

I don't describe the new function in the documentation currently because it's unstable and the usage would be updated.
