### ISSUE TITLE
feat: join all the contents in a pair

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#35]
## References
- [Bracket Lens](https://github.com/wraith13/bracket-lens-vscode) for VSCode

## TODO
- [x] Introduce `g:doppelganger#text#max_column_width`. #37 
- [x] Detect all the lines until max length to be (modified and) shown.
- [x] Add `g:doppelganger#text#shim_to_join`.
- [x] Join all the detected lines in a corresponding vitualtext.
- [x] Adjust truncate-width for texts including unicode characters.
