### ISSUE TITLE
feat: set max column to trim vitualtexts

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#37]
## TODO
- [x] Refactor text manipulation parts into another file.
- [x] Introduce `g:doppelganger#text#max_column_width`, whose default value is set to `&tw`.
- [x] Add usage of `b:doppelganger_text_max_column_width` in documentation how to set to this variable the larger value of either `&tw` and `g:doppelganger#text_max_column_width` from `ftplugin/`.
