### ISSUE TITLE
feat(text): rewrite doppelganger#text#new() to be independent from search's structure

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#48]
## TODO
- [ ] Arguments should be current lnum (and corresponding lnum, optionally)
- [ ] Without corresponding lnum, create a new instance of `doppelganger#search#new()`.
      - [ ] Replace `doppelganger#search#get_pair_info()` with `doppelganger#search#new()`.
