### ISSUE TITLE
feat(text): set other highlight groups at virtualtext

### ISSUE THREAD

**Issue by kaile256** [kaile256/vim-doppelganger#54]
## TODO
- [ ] Set another highlight group for
    - [ ] prefix
    - [ ] contents
    - [ ] shims
    - [ ] ellipisis

- [ ] Add `g:doppelganger#text#filetype2hl_groups`, whose structure will be as the code below.
    - [ ] Use `_` as default value.
    - [ ] Add `g:doppelganger#text#filetype2hl_groups_reverse`, too.
    - [ ] Enable `b:..._filetype2hl_groups` and `b:.._reverse`, too.
```vim
let g:doppelganger#text#filetype2hl_groups = {
    \ '<filetype>':  {
    \     '_': <default>,
    \     'match': <match>,
    \     'prefix': <prefix>,
    \     'contents': <contents>,
    \     'shims': <shims>,
    \     }
    \ }
```
